---
- hosts: 172.27.11.100
  tasks:
    - name: Instalando algumas dependencias
      apt:
        name: "{{ item }}"
      loop:
        - curl
        - python3
        - python3-pip
        - apt-transport-https
        - python3-setuptools
        - ntpdate

    - name: Instalando pacote Docker
      pip:
        name: docker
        executable: pip3
        
    - name: Garantindo imagem
      docker_image:
        name: "{{ item }}" 
      loop:
        - "grafana/grafana"
        - "prom/prometheus"
        - "prom/node-exporter"

    - name: Clonando repositório
      git:
        repo: https://github.com/phsmith/rundeck_exporter.git
        dest: /home/cafe/rundeck/

    - name: Buildando imagem do rundeck_exporter
      shell: docker build -t rundeck_exporter /home/cafe/rundeck/



    - name: Subindo stack completa com docker-compose
      docker_service:
        project_name: rundeck-monitoring
        definition:
          version: '3'
          volumes:
            grafana-storage:
            prometheus-storage:
          services:
            node_exporter:
              image: prom/node-exporter:latest
              container_name: node-exporter
              volumes:
                - /proc:/host/proc:ro
                - /sys:/host/sys:ro
                - /:/rootfs:ro
              command:
                - '--path.procfs=/host/proc'
                - '--path.rootfs=/rootfs'
                - '--path.sysfs=/host/sys'
              ports:
                - 9100:9100
            prometheus:
              image: prom/prometheus:latest      
              container_name: prometheus
              volumes:
                - prometheus-storage:/prometheus
                - /home/cafe/prometheus.yml:/etc/prometheus/prometheus.yml
              command:
                - '--storage.tsdb.path=/prometheus'
                - '--config.file=/etc/prometheus/prometheus.yml'
              ports:
                - 9090:9090
            grafana:
              image: grafana/grafana
              container_name: grafana
              ports:
                - 3000:3000
              volumes:
                - grafana-storage:/var/lib/grafana
            rundeck-exporter:
              image: rundeck_exporter
              container_name: rundeck-exporter
              environment:
                - RUNDECK_TOKEN=AR80VGW9H37mdIi4B1lMK6UNIb33mdMo
                - RUNDECK_URL=http://172.27.11.10:4440
                - RUNDECK_EXPORTER_HOST=0.0.0.0
                - RUNDECK_SKIP_SSL=True
                - RUNDECK_PROJECTS_EXECUTIONS=True
                - RUNDECK_CPU_STATS=True
                - RUNDECK_MEMORY_STATS=True
                - RUNDECK_API_VERSION=40
              ports:
                - 9620:9620
