{
 "title": "Rundeck Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_cpu_loadAverage_ratio",
     "legendFormat": "Load Averege"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rundeck_system_info\n" }
   ]
  },
  {
   "title": "API Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rundeck_system_info" }
   ]
  },
  {
   "title": "Last execution of job \"MySQL\"",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rundeck_project_start_timestamp{job_name=\"MySQL\"}"
    }
   ]
  },
  {
   "title": "Last execution of job \"Monitoring Stack\"",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rundeck_project_start_timestamp{job_name=\"Monitoring Stack\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rundeck_system_info" }
   ]
  },
  {
   "title": "Uptime since",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_uptime_since"
    }
   ]
  },
  {
   "title": "Last execution of job \"Create Grafana container\"",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rundeck_project_start_timestamp{job_name=\"Create Grafana container\"}"
    }
   ]
  },
  {
   "title": "Last execution of job \"Docker\"",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rundeck_project_start_timestamp{job_name=\"Docker\"}"
    }
   ]
  },
  {
   "title": "Last executions",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "rundeck_project_execution_status == 1"
    },
    {
     "expr": "rundeck_project_start_timestamp"
    }
   ]
  }
 ]
}