---
- hosts: 172.27.11.100
  tasks:
    - name: Instalando algumas dependencias
      apt:
        name: "{{ item }}"
      loop:
        - curl
        - python3
        - python3-pip
        
    - name: Instalando pacote Docker
      pip:
        name: docker
        executable: pip3
        
    - name: Garantindo imagem
      docker_image:
        name: "grafana/grafana"
    
    - name: Subindo container do grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        detach: yes
        ports:
          - "3000:3000"
        
